apiVersion: v1
kind: Service
metadata:
  name: wildfly
spec:
  type: NodePort
  selector:
    app: wildfly
  ports:
  - name: normal
    protocol: TCP
    port: 9990
    targetPort: 9990
  - name: web
    protocol: TCP
    port: 8080
    targetPort: 8080

